### ISSUE TITLE
宕机事故

### ISSUE THREAD

**Issue by LittleFall** [kernelbin/BOIT#10]
![Screenshot_20200315_152920_com tencent tim](https://user-images.githubusercontent.com/30543181/76697406-cc4cba80-66d1-11ea-9f57-6cc9cb0b4453.jpg)

文字版本：
      ———————— 2020-03-15 ————————

ikun | 中国之王的小粉丝 15:25:43
#cf profile 古老的预言提到，CN_有一位名字以z结束的wang，他的出生年份是2002，他是谁呢？

SteveBot 15:25:43
查询中...这可能要一点时间

ikun | 中国之王的小粉丝 15:26:02
[图片]

ikun | 中国之王的小粉丝 15:26:43
太长了吗

ikun | 中国之王的小粉丝 15:26:52
#cf profile CN_有一位名字以z结束的wang，他的出生年份是2002

ikun | 中国之王的小粉丝 15:27:02
#help

ikun | 中国之王的小粉丝 15:27:08
宕机了吗

ikun | 中国之王的小粉丝 15:27:10
[图片]

ikun | 中国之王的小粉丝 15:27:27
#qwq

ikun | 中国之王的小粉丝 15:29:13
#qwq

是因为查询太长了吗

**Comment by kernelbin** [comment]
目前来看这是一个bug导致的软件异常退出。现在正在排查原因

**Comment by yz-hs** [comment]
orz

**Comment by kernelbin** [comment]
由于没有正确计算URI Encode可能产生的最大长度缓冲区，引起了这一bug。已经修复。
